# Usage:
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew bundle --global

brew "clang-format"
brew "cmake"
brew "codespell"
brew "cppcheck"
brew "doxygen"
brew "ffmpeg"
brew "gcc"
brew "gifsicle"
brew "git"
brew "lcov"
brew "llvm"
brew "make"
brew "ncdu"
brew "neovim"
brew "ninja"
brew "podman"
brew "tldr"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"

cask "android-studio"
cask "appcleaner"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "inkscape"
cask "kdenlive"
cask "kitty"
cask "krita"
cask "mpv"
cask "nextcloud"
cask "obsidian"
cask "qbittorrent"
cask "sublime-text"
cask "sweet-home3d"
cask "telegram"
cask "the-unarchiver"
cask "yandex"
