[colors.primary]
background = '#1c1c1c'
foreground = '#e4e4e4'

[colors.cursor]
text    = '#1c1c1c'
cursor  = '#e4e4e4'

[colors.normal]
black   = '#262626'
red     = '#ff5f5f'
green   = '#87d75f'
yellow  = '#ffd700'
blue    = '#87afd7'
magenta = '#afafd7'
cyan    = '#afd7af'
white   = '#e4e4e4'

[colors.bright]
black   = '#8a8a8a'
red     = '#ff6f6f'
green   = '#97e76f'
yellow  = '#ffe710'
blue    = '#97bfe7'
magenta = '#bfbfe7'
cyan    = '#bfe7bf'
white   = '#eeeeee'
